image: k33g/i-am-learning-rust:0.0.1

tasks:
  - name: initialize
    before: |
      echo "🚀 before"
      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env
      wasmedge --version

    init: |
      echo "🚀 initialize"
      source /home/gitpod/.cargo/env

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - bungcip.better-toml
    - aaron-bond.better-comments
    - matklad.rust-analyzer
