image: k33g/i-am-learning-rust:0.0.0

tasks:
  - name: initialize
    before: |
      echo "🚀 before"

    init: |
      echo "🚀 initialize"
      source "/workspace/.cargo/env" && \

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments

